print("Vamos a ingresar un numero para mostrarte su raiz cuadrada y su raiz cubica.")
numero=int(input("Numero: "))
raiz2=numero**(1/2)
raiz3=numero**(1 / 3)
print(f"La raiz cuadrada del numero es: {raiz2}\nLa cubica es: {raiz3}")
input()